export {SliderHomeComponent } from "./slider-home/slider-home.component";
export {MyTixsComponent } from "./my-tixs/my-tixs.component";
export { LoginComponent } from "./login/login.component";
export { PartnersComponent } from "./partners/partners.component";
export { AffiliatesComponent } from "./affiliates/affiliates.component";
export { AffiliateDetailComponent } from "./affiliate-detail/affiliate-detail.component";
export { PartnerDetailComponent } from "./partner-detail/partner-detail.component";
export { TixDetailComponent } from "./tix-detail/tix-detail.component";
export { SignupComponent } from "./signup/signup.component";
export { NewMemberComponent } from "./new-member/new-member.component";
export { ComingComponent } from "./coming/coming.component";
export { AlltixsComponent } from "./alltixs/alltixs.component";
export { PartnerComponent } from "./new-member/partner/partner.component";
export { AffiliateComponent } from "./new-member/affiliate/affiliate.component";
export { ProfileComponent } from "./profile/profile.component";
export { AddtixsComponent } from "./addtixs/addtixs.component";
export { BookingComponent } from "./booking/booking.component";
export { AlltixslistComponent } from "./alltixslist/alltixslist.component";
export { AlltixsleftComponent } from "./alltixsleft/alltixsleft.component";
export { AboutComponent } from "./about/about.component";
export { TreksComponent } from "./treks/treks.component";
export { TreklistComponent } from "./treklist/treklist.component";
export { TrekeditComponent } from "./trekedit/trekedit.component";
export { ContactoComponent } from "./contacto/contacto.component";
export { ValidationComponent } from "./validation/validation.component";
export { CheckoutComponent } from "./checkout/checkout.component";
export { ValistComponent } from "./valist/valist.component";
export { SuccessbookComponent } from "./successbook/successbook.component";
export { SuccessaComponent } from "./successa/successa.component";
export { SuccesscontactComponent } from "./successcontact/successcontact.component";
export { CancelbookComponent } from "./cancelbook/cancelbook.component";
export { SuccesscancelbookComponent } from "./successcancelbook/successcancelbook.component";
export { AssbookComponent } from "./assbook/assbook.component";
export { DeletevalidationComponent } from "./deletevalidation/deletevalidation.component";
export { SuccessdeletevalidationComponent } from "./successdeletevalidation/successdeletevalidation.component";
export { SuccessvalidationComponent } from "./successvalidation/successvalidation.component";


